export interface Position {
  x: number;
  y: number;
}

export interface Entity {
  id: string;
  type: string;           // E.g. 'Player', 'Box', 'Wall', 'Goal', 'Laser'
  position: Position;
  properties?: Record<string, any>; // Dynamic properties like { color: 'red', damage: 10, pushable: true }
}

export type TriggerType = 'ON_START' | 'ON_STEP' | 'ON_COLLISION';

export interface Condition {
  subject: 'SELF' | 'TARGET' | 'GLOBAL'; // What are we checking?
  property: string;                      // E.g., 'type', 'hp', 'color'
  operator: '==' | '!=' | '>' | '<';
  value: any;
}

export interface Action {
  type: 'MOVE' | 'DESTROY' | 'WIN_GAME' | 'LOSE_GAME' | 'CHANGE_PROPERTY';
  payload: any; // E.g., { dx: 1, dy: 0 } for MOVE
}

export interface Rule {
  trigger: TriggerType;
  conditions: Condition[];
  actions: Action[];
}

export interface PuzzleMechanics {
  grid_width: number;
  grid_height: number;
  rules: Rule[]; // Custom global logic rules generated by AI
}

export interface PuzzleData {
  id: string;
  title: string;
  instruction_manual: string; // Markdown formatted instructions
  mechanics: PuzzleMechanics;
  entities: Entity[];
}
